project_id = "qgtxhkiqhosevopzxsdk"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
external_url = "https://qgtxhkiqhosevopzxsdk.supabase.co"

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
enabled = true
port = 54322
pooler_enabled = false
major_version = 15

[edge_functions]
enabled = true
port = 54323

[functions.send-report-email]
verify_jwt = false

[storage]
enabled = true
port = 54324
file_size_limit = "50MiB"

[studio]
enabled = true
port = 54323