// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgtxhkiqhosevopzxsdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFndHhoa2lxaG9zZXZvcHp4c2RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTE3ODYsImV4cCI6MjA3MzM2Nzc4Nn0.pjUDSooteJcyaPvd6TSyKfEDT8h8AGnDN7L-6dAV9Q8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});